# Lo pilla bien todo
/rosbot1/bt_navigator:
      ros__parameters:
        use_sim_time: True                  # SI
        global_frame: rosbot1/map           # SI
        robot_base_frame: rosbot1/base_link # SI
        odom_topic: rosbot1/odom            # SI
        enable_groot_monitoring: True       # SI
        groot_zmq_publisher_port: 1666      # SI
        groot_zmq_server_port: 1667         # SI
        default_bt_xml_filename: /home/richard/ros2_ws/install/nav2_bt_navigator/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml # SI
        plugin_lib_names:
        - nav2_compute_path_to_pose_action_bt_node      # SI
        - nav2_follow_path_action_bt_node               # SI
        - nav2_back_up_action_bt_node                   # SI
        - nav2_spin_action_bt_node                      # SI
        - nav2_wait_action_bt_node                      # SI
        - nav2_clear_costmap_service_bt_node            # SI
        - nav2_is_stuck_condition_bt_node               # SI
        - nav2_goal_reached_condition_bt_node           # SI
        - nav2_goal_updated_condition_bt_node           # SI
        - nav2_initial_pose_received_condition_bt_node  # SI
        - nav2_reinitialize_global_localization_service_bt_node # SI
        - nav2_rate_controller_bt_node                  # SI
        - nav2_distance_controller_bt_node              # SI
        - nav2_speed_controller_bt_node                 # SI
        - nav2_truncate_path_action_bt_node             # SI
        - nav2_goal_updater_node_bt_node                # SI
        - nav2_recovery_node_bt_node                    # SI
        - nav2_pipeline_sequence_bt_node                # SI
        - nav2_round_robin_node_bt_node                 # SI
        - nav2_transform_available_condition_bt_node    # SI
        - nav2_time_expired_condition_bt_node           # SI
        - nav2_distance_traveled_condition_bt_node      # SI

/rosbot1/bt_navigator_rclcpp_node:
    ros__parameters:
      use_sim_time: True

# A medias
/rosbot1/controller_server:
    ros__parameters:
      use_sim_time: True
      odom_topic: /rosbot1/odom
      controller_frequency: 10.0
      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 1.0
      min_theta_velocity_threshold: 0.001
      progress_checker_plugin: "progress_checker"
      goal_checker_plugin: "goal_checker"
      controller_plugins: ["FollowPath"]

      # Progress checker parameters
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0
      # Goal checker parameters
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.75
        stateful: True
      # DWB parameters
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        debug_trajectory_details: True
        min_vel_x: 0.0
        min_vel_y: 0.0
        max_vel_x: 0.26
        max_vel_y: 0.0
        max_vel_theta: 1.0
        min_speed_xy: 0.0
        max_speed_xy: 0.26
        min_speed_theta: 0.0
        # Add high threshold velocity for turtlebot 3 issue.
        # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
        acc_lim_x: 2.5
        acc_lim_y: 0.0
        acc_lim_theta: 3.2
        decel_lim_x: -2.5
        decel_lim_y: 0.0
        decel_lim_theta: -3.2
        vx_samples: 20
        vy_samples: 5
        vtheta_samples: 20
        sim_time: 2.5
        linear_granularity: 0.05
        angular_granularity: 0.025
        transform_tolerance: 1.0
        xy_goal_tolerance: 0.25
        trans_stopped_velocity: 0.25
        short_circuit_trajectory_evaluation: True
        stateful: True
        critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
        BaseObstacle.scale: 0.02
        PathAlign.scale: 32.0
        GoalAlign.scale: 24.0
        PathAlign.forward_point_distance: 0.1
        GoalAlign.forward_point_distance: 0.1
        PathDist.scale: 32.0
        GoalDist.scale: 24.0
        RotateToGoal.scale: 32.0
        RotateToGoal.slowing_factor: 5.0
        RotateToGoal.lookahead_time: -1.0

/rosbot1/controller_server_rclcpp_node:
    ros__parameters:
      use_sim_time: True

# Lo coje bien
/rosbot1/local_costmap:
    local_costmap:
      ros__parameters:
        update_frequency: 5.0
        publish_frequency: 2.0
        global_frame: rosbot1/odom
        robot_base_frame: rosbot1/base_link 
        use_sim_time: True
        rolling_window: true
        width: 3
        height: 3
        resolution: 0.05
        footprint: '[[0.14, 0.16], [0.14, -0.16], [-0.14, -0.16], [-0.14, 0.16]]'
        plugins: ["voxel_layer", "inflation_layer"]
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55
        voxel_layer:
          plugin: "nav2_costmap_2d::VoxelLayer"
          enabled: True
          publish_voxel_map: True
          origin_z: 0.0
          z_resolution: 0.05
          z_voxels: 16
          max_obstacle_height: 2.0
          mark_threshold: 0
          observation_sources: scan
          scan:
            topic: /rosbot1/rp_lidar/out
            max_obstacle_height: 2.0
            clearing: True
            marking: True
            data_type: "LaserScan"
            raytrace_max_range: 2.0
            raytrace_min_range: 0.0
            obstacle_max_range: 1.5
            obstacle_min_range: 0.0
        static_layer:
          map_subscribe_transient_local: True
        always_send_full_costmap: True
    local_costmap_client:
      ros__parameters:
        use_sim_time: True
    local_costmap_rclcpp_node:
      ros__parameters:
        use_sim_time: True
        
# Mas o menos lo coge tambien
/rosbot1/global_costmap:
  global_costmap:
      ros__parameters:
        update_frequency: 1.0               # SI
        publish_frequency: 1.0              # SI
        global_frame: rosbot1/map           # SI
        robot_base_frame: rosbot1/base_link # SI
        use_sim_time: True                  # SI
        footprint: '[[0.14, 0.16], [0.14, -0.16], [-0.14, -0.16], [-0.14, 0.16]]' # SI
        resolution: 0.05                    # SI
        track_unknown_space: true           # SI
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"] # SI
        obstacle_layer:                                 # NO APARECE
          plugin: "nav2_costmap_2d::ObstacleLayer"      # NO APARECE
          enabled: True                                 # NO APARECE
          observation_sources: scan                     # NO APARECE
          scan:                                         # NO APARECE
            topic: /rosbot1/rp_lidar/out                # NO APARECE
            max_obstacle_height: 2.0                    # NO APARECE
            clearing: True                              # NO APARECE
            marking: True                               # NO APARECE
            data_type: "LaserScan"                      # NO APARECE
            raytrace_max_range: 2.5                     # NO APARECE
            raytrace_min_range: 0.0                     # NO APARECE
            obstacle_max_range: 2.0                     # NO APARECE
            obstacle_min_range: 0.0                     # NO APARECE
        inflation_layer:                                # NO APARECE
          plugin: "nav2_costmap_2d::InflationLayer"     # NO APARECE
          cost_scaling_factor: 3.0                      # NO APARECE
          inflation_radius: 0.55                        # NO APARECE
        always_send_full_costmap: True    # SI

/rosbot1/global_costmap_client:
      ros__parameters:
        use_sim_time: True

/rosbot1/global_costmap:
  global_costmap_rclcpp_node:
      ros__parameters:
        use_sim_time: True

/rosbot1/planner_server:
    ros__parameters:
      use_sim_time: True
      planner_plugins: ["GridBased"] # SI
      GridBased:
        plugin: "nav2_navfn_planner/NavfnPlanner" # NO APARECE
        tolerance: 0.5                            # NO APARECE
        use_astar: false                          # NO APARECE
        allow_unknown: true          # SI

/rosbot1/planner_server_rclcpp_node:
    ros__parameters:
      use_sim_time: True

# OK
/rosbot1/robot_state_publisher:
    ros__parameters:
      use_sim_time: True

# Lo pilla a medias
/rosbot1/recoveries_server:
    ros__parameters:
      costmap_topic: local_costmap/costmap_raw            # SI
      footprint_topic: local_costmap/published_footprint  # SI
      cycle_frequency: 10.0                               # SI
      recovery_plugins: ["spin", "backup", "wait"]        # SI
      spin:                                   # NO APARECE
        plugin: "nav2_recoveries/Spin"        # NO APARECE
      backup:                                 # NO APARECE
        plugin: "nav2_recoveries/BackUp"      # NO APARECE
      wait:                                   # NO APARECE
        plugin: "nav2_recoveries/Wait"        # NO APARECE
      global_frame: rosbot1/odom            # SI
      robot_base_frame: rosbot1/base_link   # SI
      transform_timeout: 0.1                # NO APARECE
      use_sim_time: True                    # SI
      simulate_ahead_time: 2.0 # NO APARECE
      max_rotational_vel: 1.0  # NO APARECE
      min_rotational_vel: 0.4  # NO APARECE
      rotational_acc_lim: 3.2  # NO APARECE

  
/rosbot1/WaypointFollower:
    ros__parameters:
      loop_rate: 20
      stop_on_failure: false
      waypoint_task_executor_plugin: "wait_at_waypoint"   
      wait_at_waypoint:
        plugin: "nav2_waypoint_follower::WaitAtWaypoint"
        enabled: True
        waypoint_pause_duration: 200
        
